//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accinfo
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> accno { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<decimal> balance { get; set; }
        public byte[] image { get; set; }
        public string imageurl { get; set; }
    }
}
